# Generated by Django 2.2.13 on 2020-10-30 13:40

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indigo_api', '0135_auto_20201023_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('search_text', models.TextField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchable_document', to='indigo_api.Document')),
            ],
        ),
    ]
