# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 19:37
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_search_psql', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX indigo_search_psql_searchabledocument_vector ON indigo_search_psql_searchabledocument USING gin(search_vector)",
            "DROP INDEX indigo_search_psql_searchabledocument_vector",
            elidable=False
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION indigo_search_psql_search_text_trigger() RETURNS trigger AS $$
            begin
              new.search_vector :=
                 setweight(to_tsvector(coalesce(new.title,'')), 'A') ||
                 setweight(to_tsvector(coalesce(new.search_text,'')), 'B');
              return new;
            end
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER indigo_search_psql_tsvectorupdate BEFORE INSERT OR UPDATE
                ON indigo_search_psql_searchabledocument FOR EACH ROW EXECUTE PROCEDURE indigo_search_psql_search_text_trigger();
            """,
            "DROP FUNCTION IF EXISTS indigo_search_psql_tsvectorupdate() CASCADE;",
            elidable=False
        ),
    ]
